# Generated by Django 6.0.3 on 2026-03-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Atividade')),
                ('data', models.DateField(verbose_name='Data de Realização')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('imagem', models.ImageField(upload_to='atividades/', verbose_name='Foto da Atividade')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='ConteudoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_secao', models.CharField(max_length=100, verbose_name='Título da Seção')),
                ('texto_informativo', models.TextField(verbose_name='Texto sobre a ONG')),
                ('imagem', models.ImageField(upload_to='sobre/', verbose_name='Foto Informativa')),
            ],
            options={
                'verbose_name': 'Conteúdo Sobre',
                'verbose_name_plural': 'Conteúdos Sobre',
            },
        ),
        migrations.CreateModel(
            name='DestaqueInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Banner')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo/Frase')),
                ('imagem', models.ImageField(upload_to='inicio/', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Destaque de Início',
                'verbose_name_plural': 'Destaques de Início',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Integrante')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('foto', models.ImageField(upload_to='equipe/', verbose_name='Foto de Perfil')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Link do LinkedIn')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
            },
        ),
    ]
