# Generated by Django 6.0.5 on 2026-05-07 14:07

import cloudinary.models
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='CapiClima', max_length=100, verbose_name='Nome do Site')),
                ('slogan', models.CharField(blank=True, default='Juventude, Educação e Meio Ambiente', max_length=200, verbose_name='Slogan')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo do Site')),
                ('favicon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, default='coletivocapiclima@gmail.com', max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, default='(65) 9 9919-4450', max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, default='5565999194450', help_text='Apenas números, com DDI. Ex: 5565999194450', max_length=20, verbose_name='Número WhatsApp (com DDI)')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/capiclima', verbose_name='Link do Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Link do Twitter/X')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Link do Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Link do YouTube')),
                ('chave_pix', models.CharField(blank=True, default='coletivocapiclima@gmail.com', max_length=100, verbose_name='Chave Pix')),
                ('qrcode_pix', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='QR Code Pix')),
                ('texto_rodape', models.CharField(blank=True, default='Todos os direitos reservados.', max_length=200, verbose_name='Texto do Rodapé')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['-data'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='conteudosobre',
            options={'ordering': ['ordem'], 'verbose_name': 'Conteúdo Sobre', 'verbose_name_plural': 'Conteúdos Sobre'},
        ),
        migrations.AlterModelOptions(
            name='destaqueinicio',
            options={'ordering': ['ordem'], 'verbose_name': 'Destaque de Início', 'verbose_name_plural': 'Destaques de Início'},
        ),
        migrations.AlterModelOptions(
            name='membroequipe',
            options={'ordering': ['ordem'], 'verbose_name': 'Membro da Equipe', 'verbose_name_plural': 'Membros da Equipe'},
        ),
        migrations.AddField(
            model_name='atividade',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para exibir esta atividade na página inicial.', verbose_name='Destacar na página inicial?'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='local',
            field=models.CharField(blank=True, help_text='Ex: Cuiabá, MT', max_length=200, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='conteudosobre',
            name='icone',
            field=models.CharField(blank=True, help_text='Ex: fas fa-leaf, fas fa-users, fas fa-globe', max_length=50, verbose_name='Ícone Font Awesome'),
        ),
        migrations.AddField(
            model_name='conteudosobre',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='destaqueinicio',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este destaque do site.', verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='destaqueinicio',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.', verbose_name='Ordem de Exibição'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='bio',
            field=models.TextField(blank=True, help_text='Uma breve descrição sobre o membro.', verbose_name='Biografia Curta'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descrição da Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto da Atividade'),
        ),
        migrations.AlterField(
            model_name='conteudosobre',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto Informativa'),
        ),
        migrations.AlterField(
            model_name='conteudosobre',
            name='texto_informativo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto sobre a ONG'),
        ),
        migrations.AlterField(
            model_name='destaqueinicio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto de Perfil'),
        ),
    ]
