# Generated by Django 6.0.5 on 2026-05-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_configuracaosite_alter_atividade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='imagem_local',
            field=models.CharField(blank=True, help_text='Caminho relativo em static/. Ex: images/atividades/2024/atividade-012024.jpeg', max_length=200, verbose_name='Imagem Local (fallback)'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='foto_local',
            field=models.CharField(blank=True, help_text='Caminho relativo em static/. Ex: images/gestao/Gregorio.jpg', max_length=200, verbose_name='Foto Local (fallback)'),
        ),
    ]
