# Generated by Django 6.0.5 on 2026-06-08 15:49

import cloudinary.models
import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_atividade_imagem_local_membroequipe_foto_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Titulo')),
                ('descricao', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descricao')),
                ('link', models.URLField(blank=True, verbose_name='Link para inscricao')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['ordem', 'data_inicio', 'data_fim', 'titulo'],
            },
        ),
        migrations.RenameModel(
            old_name='ConfiguracaoSite',
            new_name='SiteConfig',
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome interno')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(blank=True, max_length=160, verbose_name='Titulo exibido')),
                ('texto_principal', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Texto principal')),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem')),
                ('botao_texto', models.CharField(blank=True, max_length=80, verbose_name='Texto do botao')),
                ('botao_url', models.CharField(blank=True, max_length=250, verbose_name='URL do botao')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Secao do Site',
                'verbose_name_plural': 'Secoes do Site',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Configuracao do Site', 'verbose_name_plural': 'Configuracao do Site'},
        ),
        migrations.AlterModelOptions(
            name='conteudosobre',
            options={'ordering': ['ordem'], 'verbose_name': 'Conteudo Sobre', 'verbose_name_plural': 'Conteudos Sobre'},
        ),
        migrations.AlterModelOptions(
            name='destaqueinicio',
            options={'ordering': ['ordem'], 'verbose_name': 'Destaque de Inicio', 'verbose_name_plural': 'Destaques de Inicio'},
        ),
        migrations.AddField(
            model_name='atividade',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horario',
            field=models.CharField(blank=True, max_length=80, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo da Atividade'),
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Instagram'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(verbose_name='Data de Realizacao'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descricao da Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para exibir esta atividade na pagina inicial.', verbose_name='Destacar na pagina inicial?'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto da Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='local',
            field=models.CharField(blank=True, help_text='Ex: Cuiaba, MT', max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='conteudosobre',
            name='icone',
            field=models.CharField(blank=True, help_text='Ex: fas fa-leaf, fas fa-users, fas fa-globe', max_length=50, verbose_name='Icone Font Awesome'),
        ),
        migrations.AlterField(
            model_name='conteudosobre',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto Informativa'),
        ),
        migrations.AlterField(
            model_name='conteudosobre',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao'),
        ),
        migrations.AlterField(
            model_name='conteudosobre',
            name='titulo_secao',
            field=models.CharField(max_length=100, verbose_name='Titulo da Secao'),
        ),
        migrations.AlterField(
            model_name='destaqueinicio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='destaqueinicio',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Menor numero aparece primeiro.', verbose_name='Ordem de exibicao'),
        ),
        migrations.AlterField(
            model_name='destaqueinicio',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitulo/Frase'),
        ),
        migrations.AlterField(
            model_name='destaqueinicio',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo do Banner'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografia Curta'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo/Funcao'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='slogan',
            field=models.CharField(blank=True, default='Juventude, Educacao e Meio Ambiente', max_length=200, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Logo do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp',
            field=models.CharField(blank=True, default='5565999194450', help_text='Apenas numeros, com DDI. Ex: 5565999194450', max_length=20, verbose_name='Numero WhatsApp (com DDI)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='qrcode_pix',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='QR Code Pix'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='texto_rodape',
            field=models.CharField(blank=True, default='Todos os direitos reservados.', max_length=200, verbose_name='Texto do Rodape'),
        ),
    ]
