# Generated by Django 6.0.5 on 2026-06-09 14:08

import cloudinary.models
import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0004_opportunity_siteconfig_sitesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoApoie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_voluntariado', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descrição da seção de voluntariado.', verbose_name='Texto — Voluntariado')),
                ('link_voluntariado', models.CharField(blank=True, default='/oportunidades/', help_text='URL do botão de voluntariado.', max_length=250, verbose_name='Link — Voluntariado')),
                ('texto_doacao', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descrição da seção de doação financeira.', verbose_name='Texto — Doação')),
                ('link_doacao', models.CharField(blank=True, help_text='URL do botão de doação (opcional).', max_length=250, verbose_name='Link — Doação')),
                ('texto_parcerias', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descrição da seção de parcerias empresariais.', verbose_name='Texto — Parcerias')),
                ('link_parcerias', models.CharField(blank=True, help_text='URL do botão de parcerias (opcional).', max_length=250, verbose_name='Link — Parcerias')),
                ('texto_compartilhe', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Descrição da seção 'Compartilhe'.", verbose_name='Texto — Compartilhe')),
            ],
            options={
                'verbose_name': 'Página Apoie',
                'verbose_name_plural': 'Página Apoie',
            },
        ),
        migrations.CreateModel(
            name='SecaoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(blank=True, help_text='Título exibido no banner principal da home.', max_length=160, verbose_name='Título principal (hero)')),
                ('subtitulo', models.CharField(blank=True, help_text='Frase complementar abaixo do título principal.', max_length=250, verbose_name='Subtítulo (hero)')),
                ('imagem_banner', cloudinary.models.CloudinaryField(blank=True, help_text='Imagem de fundo do hero. Recomendado: 1920×800px.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem do banner')),
                ('texto_juventudes', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Texto da seção 'Juventudes em Ação' na home.", verbose_name='Texto — Juventudes em Ação')),
                ('titulo_juventudes', models.CharField(blank=True, default='Juventudes em Ação', max_length=160, verbose_name='Título — Juventudes em Ação')),
                ('imagem_juventudes', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem — Juventudes')),
                ('titulo_parceiros', models.CharField(blank=True, default='Nossos Parceiros', max_length=160, verbose_name='Título — Parceiros')),
                ('texto_parceiros', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Texto — Parceiros')),
                ('imagem_parceiros', cloudinary.models.CloudinaryField(blank=True, help_text='Logotipos dos parceiros/apoiadores.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem — Parceiros')),
                ('titulo_cta', models.CharField(blank=True, default='Quer fazer a diferença?', help_text='Chamada para ação no final da home.', max_length=160, verbose_name='Título — CTA')),
                ('texto_cta', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Texto — CTA')),
                ('link_cta', models.CharField(blank=True, help_text='Link do botão principal da CTA.', max_length=250, verbose_name='URL do botão CTA')),
            ],
            options={
                'verbose_name': 'Página Inicial',
                'verbose_name_plural': 'Página Inicial',
            },
        ),
        migrations.CreateModel(
            name='SecaoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Sobre o CapiClima', max_length=160, verbose_name='Título da página')),
                ('texto_principal', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Texto institucional 'Quem Somos', missão, visão.", verbose_name='Texto principal')),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem institucional')),
                ('missao', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Missão')),
                ('visao', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Visão')),
                ('valores', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Valores')),
            ],
            options={
                'verbose_name': 'Página Sobre',
                'verbose_name_plural': 'Página Sobre',
            },
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='chave_pix',
            field=models.CharField(blank=True, default='coletivocapiclima@gmail.com', help_text='Chave Pix para doações (e-mail, CPF, telefone ou aleatória).', max_length=100, verbose_name='Chave Pix'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Ícone exibido na aba do navegador. Recomendado: 32×32px.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo principal do site. Recomendado: PNG com fundo transparente.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Logo do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='qrcode_pix',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagem do QR Code para pagamento via Pix.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='QR Code Pix'),
        ),
    ]
