# Generated by Django 6.0.3 on 2026-06-11 21:28

import apps.ong.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0005_secaoapoie_secaohome_secaosobre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaqueinicio',
            name='abrir_nova_aba',
            field=models.BooleanField(default=False, verbose_name='Abrir link em nova aba?'),
        ),
        migrations.AddField(
            model_name='destaqueinicio',
            name='link_botao',
            field=models.CharField(blank=True, default='', help_text='Pode ser um link interno, como /atividades/, ou externo.', max_length=250, verbose_name='Link do botão'),
        ),
        migrations.AddField(
            model_name='destaqueinicio',
            name='texto_botao',
            field=models.CharField(blank=True, default='', help_text='Ex: Saiba mais, Inscreva-se, Ver atividade.', max_length=80, verbose_name='Texto do botão'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Foto da Atividade'),
        ),
        migrations.AlterField(
            model_name='conteudosobre',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Foto Informativa'),
        ),
        migrations.AlterField(
            model_name='destaqueinicio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='membroequipe',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='secaohome',
            name='imagem_banner',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagem de fundo do hero. Recomendado: 1920×800px.', max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Imagem do banner'),
        ),
        migrations.AlterField(
            model_name='secaohome',
            name='imagem_juventudes',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Imagem — Juventudes'),
        ),
        migrations.AlterField(
            model_name='secaohome',
            name='imagem_parceiros',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logotipos dos parceiros/apoiadores.', max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Imagem — Parceiros'),
        ),
        migrations.AlterField(
            model_name='secaosobre',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Imagem institucional'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Ícone exibido na aba do navegador. Recomendado: 32×32px.', max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo principal do site. Recomendado: PNG com fundo transparente.', max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Logo do Site'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='qrcode_pix',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagem do QR Code para pagamento via Pix.', max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='QR Code Pix'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Imagem'),
        ),
    ]
