# Generated by Django 6.0.3 on 2026-06-11 21:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0006_destaqueinicio_abrir_nova_aba_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['ordem', 'data_fim', 'titulo'], 'verbose_name': 'Oportunidades — Item da Planilha', 'verbose_name_plural': 'Oportunidades — Planilha de Inscrições'},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tipo',
            field=models.CharField(blank=True, default='', help_text='Ex: Voluntariado, Oficina, Curso, Evento, Seleção, Edital.', max_length=80, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Término da inscrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da inscrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Texto curto explicando a oportunidade.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link',
            field=models.URLField(blank=True, help_text='Cole aqui o link do formulário ou página de inscrição.', verbose_name='Link de inscrição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.', verbose_name='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='titulo',
            field=models.CharField(max_length=180, verbose_name='Oportunidade'),
        ),
    ]
