# Generated by Django 6.0.3 on 2026-06-15 18:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0007_alter_opportunity_options_opportunity_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='resultados_encaminhamentos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Lista ou texto com resultados da atividade.', verbose_name='Resultados e encaminhamentos'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='temas_debatidos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Conteúdo exibido ao clicar em Ver mais.', verbose_name='Temas debatidos'),
        ),
    ]
