# Generated by Django 6.0.3 on 2026-06-17 22:07

import apps.ong.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0008_atividade_resultados_encaminhamentos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do parceiro')),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, help_text='Logo ou imagem do parceiro/apoiador.', max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='Imagem/logo')),
                ('link', models.URLField(blank=True, help_text='Ao clicar na imagem, o visitante será enviado para este link.', verbose_name='Link')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Página Inicial — Parceiro',
                'verbose_name_plural': 'Página Inicial — Parceiros',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
