# Generated by Django 5.2.15 on 2026-06-19 02:59

import apps.ong.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0009_parceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='secaoapoie',
            name='pix',
            field=models.CharField(blank=True, default='', help_text='Chave Pix para doações (e-mail, CPF, telefone ou aleatória).', max_length=100, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='secaoapoie',
            name='qrcode_pix',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagem do QR Code para pagamento via Pix.', max_length=255, null=True, validators=[apps.ong.models.image_extension_validator], verbose_name='QR Code Pix'),
        ),
    ]
