# Generated by Django 5.2.15 on 2026-06-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0011_copiar_pix_para_apoie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='qrcode_pix',
        ),
    ]
