# Generated by Django 5.2.15 on 2026-06-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0012_remove_pix_from_siteconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secaoapoie',
            name='link_doacao',
        ),
        migrations.RemoveField(
            model_name='secaoapoie',
            name='link_parcerias',
        ),
        migrations.RemoveField(
            model_name='secaoapoie',
            name='link_voluntariado',
        ),
        migrations.RemoveField(
            model_name='secaoapoie',
            name='texto_compartilhe',
        ),
        migrations.RemoveField(
            model_name='secaoapoie',
            name='texto_doacao',
        ),
        migrations.RemoveField(
            model_name='secaoapoie',
            name='texto_parcerias',
        ),
        migrations.RemoveField(
            model_name='secaoapoie',
            name='texto_voluntariado',
        ),
    ]
