# Generated by Django 5.2.15 on 2026-06-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0013_remove_texto_fields_from_secaoapoie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='texto_rodape',
        ),
    ]
